-- Estrutura 


-- 3 

CREATE TABLE USR_GESTAO_HOTEL.CLIENTES (
    CLIENTE_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    TELEFONE VARCHAR2(15),
    PRIMARY KEY (CLIENTE_ID)
);

CREATE TABLE USR_GESTAO_HOTEL.QUARTOS (
    QUARTO_ID NUMBER NOT NULL,
    NUMERO VARCHAR2(10) NOT NULL,
    TIPO VARCHAR2(50),
    PRECO_DIARIA NUMBER(10,2),
    PRIMARY KEY (QUARTO_ID)
);

CREATE TABLE USR_GESTAO_HOTEL.RESERVAS (
    RESERVA_ID NUMBER NOT NULL,
    CLIENTE_ID NUMBER NOT NULL,
    QUARTO_ID NUMBER,
    DATA_CHECKIN DATE,
    DATA_CHECKOUT DATE,
    STATUS VARCHAR2(50),
    PRIMARY KEY (RESERVA_ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES USR_GESTAO_HOTEL.CLIENTES(CLIENTE_ID),
    FOREIGN KEY (QUARTO_ID) REFERENCES USR_GESTAO_HOTEL.QUARTOS(QUARTO_ID)
);

CREATE TABLE USR_GESTAO_HOTEL.PEDIDOS (
    PEDIDO_ID NUMBER NOT NULL,
    CLIENTE_ID NUMBER NOT NULL,
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMBER(10,2),
    STATUS VARCHAR2(50),
    PRIMARY KEY (PEDIDO_ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES USR_GESTAO_HOTEL.CLIENTES(CLIENTE_ID)
);

CREATE TABLE USR_GESTAO_HOTEL.ITENS_PEDIDO (
    ITEM_PEDIDO_ID NUMBER NOT NULL,
    PEDIDO_ID NUMBER NOT NULL,
    NOME_ITEM VARCHAR2(100) NOT NULL,
    QUANTIDADE NUMBER NOT NULL,
    PRECO_UNITARIO NUMBER(10,2),
    PRIMARY KEY (ITEM_PEDIDO_ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES USR_GESTAO_HOTEL.PEDIDOS(PEDIDO_ID)
);


